### ISSUE TITLE
Scope constraints

### ISSUE THREAD

**Issue by Startouf** [siliconsenthil/commit_param_routing#2]
I'd like to be able to reuse the same path helper, but either I cannot figure the right way to write th routes, or it's impossible.

```
I'm trying to do something like that

resource :employees do
  patch 'mass_update', on: :collection, as: 'mass_update' do
    scope constraints: CommitParamRouting.new('publish'), action: 'mass-publish'
    scope constraints: CommitParamRouting.new('unpublish'), action: 'mass-unpublish'
    ...
  end
end
```

The above code compiles, but there is no filtering done. the first line `patch` doesn't have a constraint and is matched automatically, without the need to evaluate the nested constraints

**Comment by siliconsenthil** [comment]
As of now, nested constraints are not available. Contributions welcome. :+1:
